### ISSUE TITLE
Support phpunit 8

### ISSUE THREAD

**Issue by tadasaa** [Codeception/phpunit-wrapper#60]
The `phpunit ">=7.1 <7.6"` limitation does not allow to migrate to phpunit 8.

**Comment by Naktibalda** [comment]
I was waiting for this ticket to be raised :)
Now please review https://github.com/Codeception/phpunit-wrapper/pull/59 and https://github.com/Codeception/Codeception/compare/2.5...2.6?expand=1 (don't raise pull request for this one).

**Comment by Naktibalda** [comment]
If you are very keen to use PHPUnit 8, set version constraint of `codeception/codeception` to `dev-2.6` and run `composer update`.
Please let me know if you have any unexpected issues.

PHPUnit backwards compatibility breaks are expected issues.
If your tests fail, because `setUp`, `tearDown`, `setUpBeforeClass`  or `tearDownAfterClass` now requires `: void` return type, you have 2 options:
* append `: void`.
* prepend `_` to method name, e.g. `_setUp`. This approach works if test extends `Codeception\Test\Unit`. If your test extends `PHPUnit\Framework\Testcase`, you get `_setUp` by making it extends `Codeception\PHPUnit\Testcase` instead.

If your test fails because they use `assertContains` or `@expectException` annotation, you have no choice but to fix your tests.
`assertStringContainsString` and `expectException` method families will be added to `PHPUnit\Framework\Testcase` and will be available in tests extending that class or  `Codeception\Test\Unit` and through `Asserts` module, so it will be possible to use them with old versions of PHPUnit.

https://github.com/Codeception/phpunit-wrapper/blob/8.0/src/TestCase.php

PhpUnit 8 support is complete, but a bit more work is required to support older versions of PHPUnit in 2.6.

**Comment by Naktibalda** [comment]
Actually `expectException` exists in all supported versions of PHPUnit.

**Comment by Naktibalda** [comment]
Remaining items:
* add `assertIsInt` family of methods to \Codeception\PHPUnit\TestCase` in 7.1, 6.5 and 7.0 branches.
`assertIsInt` and `assertIsString` are used in Codeception tests, but it would be nice to add them all.
* get `Codeception\Stub` tests pass https://github.com/Codeception/Stub/pull/15

**Comment by Naktibalda** [comment]
Supported since Codeception 3.0.0
