### ISSUE TITLE
SelfDescribing interface is incompatible with phpunit 7/8

### ISSUE THREAD

**Issue by mischka** [Codeception/phpunit-wrapper#63]
The interface SelfDescribing in the file phpunit7-interfaces.php is incompatible with phpunit 7.5 and 8.2

https://github.com/sebastianbergmann/phpunit/blob/7.5/src/Framework/SelfDescribing.php
https://github.com/sebastianbergmann/phpunit/blob/8.2/src/Framework/SelfDescribing.php

The method toString has not return type
```
    /**
     * Returns a string representation of the object.
     */
    public function toString(): string;
```

I think this is related to this issue https://github.com/Codeception/Codeception/issues/5031

**Comment by emulgeator** [comment]
4 month old ticket and not even a comment. 
Is this package maintained at all?

**Comment by Naktibalda** [comment]
@emulgeator creator of this issue commented on linked issue an received some responses.

The root cause was that he used Codeception and php-mock/php-mock-phpunit and both libraries have workarounds to be compatible with different major versions of PHPUnit and workarounds of php-mock-phpunit interfered with workarounds of Codeception or another way around.
Look at https://github.com/Codeception/Codeception/issues/5031 for more information.

**Comment by Naktibalda** [comment]
This issue won't exist in Codeception 5.0 which drops support for old versions of PHPUnit: #6067
